"""add hashed_password to users

Revision ID: a5a647461f92
Revises: edb175a1de9f
Create Date: 2026-02-22 04:44:55.734598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5a647461f92'
down_revision: Union[str, None] = 'edb175a1de9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_slug', table_name='products')
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=True)
    op.alter_column('rooms', 'rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('4.0'))
    op.alter_column('rooms', 'review_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_column('rooms', 'is_available')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('is_available', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.alter_column('rooms', 'review_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('rooms', 'rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('4.0'))
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    op.create_index('ix_products_slug', 'products', ['slug'], unique=False)
    # ### end Alembic commands ###
